# Generated by Django 2.2.1 on 2019-05-27 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(max_length=12)),
                ('fCMToken', models.CharField(max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='gamer',
            name='fCMToken',
        ),
        migrations.RemoveField(
            model_name='gamer',
            name='phoneNumber',
        ),
        migrations.AddField(
            model_name='gamer',
            name='person',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.Person'),
            preserve_default=False,
        ),
    ]
