# Generated by Django 2.2.1 on 2019-05-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190527_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesession',
            name='gamers',
        ),
        migrations.AddField(
            model_name='gamesession',
            name='players',
            field=models.ManyToManyField(to='api.Person'),
        ),
        migrations.DeleteModel(
            name='Gamer',
        ),
    ]
