# Generated by Django 2.2.1 on 2019-05-27 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190528_0455'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='currentPlayerNumber',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='finishedPlayerNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='readyPlayerNumber',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='spyNumber',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='totalNumberOfPlayers',
            field=models.IntegerField(default=4),
        ),
    ]
